### ISSUE TITLE
Non-functional on Ubuntu 20.04

### ISSUE THREAD

**Issue by MathNodes** [DEROFDN/Engram#1]
Because Ubuntu 20.04, although still in LTS until April 2025, Engram will not work on here unless you upgrade your GLIB C - which I **DO NOT** recommend until Ubuntu does it officially. It may break many packages on your machine. 

# Output

```shell
$ ./Engram 
./Engram: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./Engram)
./Engram: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./Engram)

$ ldd --version
ldd (Ubuntu GLIBC 2.31-0ubuntu9.9) 2.31

```
I'll continue using CLI until either Ubutnu upgrades or I move to 22.04, which ever one comes first.

**Comment by aguythere** [comment]
Please reopen this ticket. This is STILL a problem. Fixing it requires upgrading libc to 2.34 or above, which for me was relatively painless, but there are many people for whom upgrading their computers is a huge hassle and causes a ton of additional work to get active. Obviously upgrading is the best option, but it shouldn't be mandatory.
