### ISSUE TITLE
Installing on Ubuntu

### ISSUE THREAD

**Issue by vadim-on-github** [DEROFDN/Engram#10]
Anyone have a link or can provide a (preferably video) tutorial / walk-through on how to install/build/run Engram on Ubuntu?

**Comment by mrbluecoat** [comment]
Same issue. I load my seed phrase, it detects my account, but of the three buttons at the bottom the left-most stays yellow and the wallet doesn't load.

Ref #7 #9 #12

**Comment by vadim-on-github** [comment]
@mrbluecoat irrelevant

**Comment by mrbluecoat** [comment]
Sorry, I thought you were having trouble running on Ubuntu

**Comment by vadim-on-github** [comment]
yes, but only installing and running Engram GUI wallet. According to your comment, you've already installed/ran it and are seeing its GUI

**Comment by Nelbert442** [comment]
Please download or build from latest release https://github.com/DEROFDN/Engram/releases/latest and feel free to re-open relevant issues should you still encounter them.
