### ISSUE TITLE
problem with walet. Cant open

### ISSUE THREAD

**Issue by ecostar11** [DEROFDN/Engram#12]
Problem cant open. what do the 3 indicators at the bottom mean. When the wallet was working normally, they were green. And the central one was illuminated. Now when the gamenel does not open. They are highlighted in yellow and the left one is highlighted

**Comment by Fka27ADA-mod** [comment]
@ecostar11 Have you gotten any help and able to resolved your issues?

**Comment by Nelbert442** [comment]
Please download or build from latest release https://github.com/DEROFDN/Engram/releases/latest and feel free to re-open relevant issues should you still encounter them.
