### ISSUE TITLE
engram wallet

### ISSUE THREAD

**Issue by Dogsbreathe** [DEROFDN/Engram#13]
hi 

i hope this message finds you well,

for the the last month or so i have opened my wallet and within a minute it closes it self down, whether i put a password in or not.

any help would be greatly appreciated,

i have my wallet on an apple mac

**Comment by jmynheir** [comment]
I have the same problem.  If you remove the datashards and mainnet folder in the working directory and restore your wallet from seed it will work again, for awhile until it doesn't.  If it helps the devs here is the output when I run Engram from command line.
````
Copyright 2020-2022 DERO Foundation. All rights reserved.
OS:linux ARCH:amd64 GOMAXPROCS:8

2023/03/25 15:26:05 Trying to connect...
2023/03/25 15:26:05 [Connect] Connection to RPC server successful - ws://192.168.0.27:54040/ws
2023/03/25 15:26:05 Fyne error:  could not load SVG, falling back to static content:
2023/03/25 15:26:05   Cause: XML syntax error on line 3: invalid UTF-8
2023/03/25 15:26:05   At: /home/dank/go/pkg/mod/fyne.io/fyne/v2@v2.2.2/internal/svg/svg.go:27
2023/03/25 15:26:05 Fyne error:  could not load SVG, falling back to static content:
2023/03/25 15:26:05   Cause: XML syntax error on line 3: invalid UTF-8
2023/03/25 15:26:05   At: /home/dank/go/pkg/mod/fyne.io/fyne/v2@v2.2.2/internal/svg/svg.go:27
2023/03/25 15:26:05 Fyne error:  could not load SVG, falling back to static content:
2023/03/25 15:26:05   Cause: XML syntax error on line 3: invalid UTF-8
2023/03/25 15:26:05   At: /home/dank/go/pkg/mod/fyne.io/fyne/v2@v2.2.2/internal/svg/svg.go:27
2023/03/25 15:26:12 [AddSCIDToIndex] Hardcoded SCID matches search filter. Adding SCID 0000000000000000000000000000000000000000000000000000000000000001
[Gnomon] Scan Status: [1019514 / 1019514]
2023/03/25 15:26:14 [indexBlock] SCID matches search filter. Adding SCID a05395bb0cf77adc850928b0db00eb5ca7a9ccbafd9a38d021c8d299ad5ce1a4 / Signer 
2023/03/25 15:26:15 [indexBlock] TXID '5968c0e18b9cd4c73a616a4465c54a6364a749ce1959ab8c75f921dec2163e12' has SCID in payload of 'fb137cba2f0fab75c9cc5e1f896b68204300f546ea58d6bc9556b9f0f640f8bc' and ring members: [dero1qyzgusqg2jnhle5l6t5euym66nt2n6cljulvcd3038zewwrxkpx0yqqwm9u24 dero1qykxqmxv8549ue9vcp5rz2p3lje0g4xryezj05c79x08ykvgqp83kqqm0j329 dero1qyrw3jwkpvc6xc3dy8q4244zul4dyczktqyjg07mllf8j666w76mvqgt36etn dero1qycqhnsn0dynkaagyqxwmcz0nsydpvfv6hd3v4e2avna5qztz729kqgkf2kz9 dero1qyr9scmdelmydzwmwftnav9u4nhjzd64s2vrrwdhfp0ptm2a9hyzsqgy5ma6p dero1qyfq8m3rju62tshju60zuc0ymrajwxqajkdh6pw888ejuv94jlfgjqq58px98 dero1qy4qd8lry2hefufkyadsh25fhp3xsj0f249u9yarzjk6tk9dad5u7qqh5462w dero1qysahyz0vph2gf34sjtd70rdtufa68hfzcw9hm4twk9kqqnjsu87cqg0luu6d dero1qyyym3fz80tcztlhl04uu5svpq5k2mlrm2jmpgeatjd26vy78s85vqgkz8ull dero1qyjq5jlcpyxvuppv2dm5vqkxf3n2n62fu74zq0vpymrmksn9ek02cqg42z8g0 dero1qyvgjlyja3mscjlspr6np0leuk3smdqnwerf82h7rxch56rwcp7ysqgmdnkul dero1qy9v0zvqcss8ygc7a892z63jgm749ys3c480mf6xtpu7hkx659tj2qg5z5ywa dero1qyg3kcmac84paknn2y93axew43d7kq27t6nx57q85qyuklc755hr5qg7pqad2 dero1qyrflrrm0ml77pvm5dm3mt8sgs7q7qtem60ycms5pcqgwpkpmfsagqg2zkgdh dero1qy9nk7eftyzu726pl2v5s9fxas9we8fjl6yeqsn2u4q2xywur868vqgg8h0pn dero1qy0g0dgljrhd7ns955m5d47d3mdk7tu8a64yxxw9dk620t9gxjklkqq84nl0g].
panic: runtime error: index out of range [1] with length 1

goroutine 103 [running]:
github.com/civilware/Gnomon/indexer.(*Indexer).indexBlock.func1(0x0)
        /home/dank/go/pkg/mod/github.com/civilware/!gnomon@v0.0.0-20220722181952-20e0bfc5c13d/indexer/indexer.go:642 +0x109c
created by github.com/civilware/Gnomon/indexer.(*Indexer).indexBlock
        /home/dank/go/pkg/mod/github.com/civilware/!gnomon@v0.0.0-20220722181952-20e0bfc5c13d/indexer/indexer.go:567 +0x5e6
```
`

**Comment by Dogsbreathe** [comment]
thanks will give it a try

**Comment by Dogsbreathe** [comment]
i have now managed to do this but it will only let me do it for one of my accounts - the other one lets me get right to the end and i press recover and it just closes down - so i loaded engram on to a different computer and it still wouldn't let me import my second wallet from seed got all the way to the end and it just closes - dont understand why it let me do one wallet without the other - any help gratly appreciated - thanks

**Comment by jmynheir** [comment]
uncheck "enable gnomon" in the settings, Mine has been stable after I did it

**Comment by nosaj965** [comment]
Hey guys I'm having the dsame issue basically.  I open it and it closes before I can put password in.  So i deleted it and reloaded it only to have the same thing happen.  Any ideas?

**Comment by agentmic487** [comment]
> Hey guys I'm having the dsame issue basically. I open it and it closes before I can put password in. So i deleted it and reloaded it only to have the same thing happen. Any ideas?

Hi mate, are you still having this issue or got it solved? If not you can get in touch with me so we can both get it solved together because a lot of people have come with same complain and it work for them i believe we can solve this together...Don't wait to say hi

**Comment by agentmic487** [comment]
> i have now managed to do this but it will only let me do it for one of my accounts - the other one lets me get right to the end and i press recover and it just closes down - so i loaded engram on to a different computer and it still wouldn't let me import my second wallet from seed got all the way to the end and it just closes - dont understand why it let me do one wallet without the other - any help gratly appreciated - thanks

Hi mate, are you still having this issue or got it solved? If not you can get in touch with me so we can both get it solved together because a lot of people have come with same complain and it work for them i believe we can solve this together...Don't wait to say hi

**Comment by Nelbert442** [comment]
Please download or build from latest release https://github.com/DEROFDN/Engram/releases/latest and feel free to re-open relevant issues should you still encounter them.
