### ISSUE TITLE
Strange errors during POW registration.

### ISSUE THREAD

**Issue by aguythere** [DEROFDN/Engram#14]
Some errors I could find nothing about with a search pop up during the POW registration step. I am still attempting to register so I don't know if this is a critical error but I get more on the console after a few of them so I'm going to assume it's non-critical.

```
[GetSCVariables] ERROR - GetSCVariables failed: [-32098] max 1024 variables can be returned.
```
This is the error I get. I'm not even sure what else I should post, except what OS I am using and libc version....

OS is Devuan Chimaera kernel version 5.10.0-21-amd64. Libc version (Debian GLIBC 2.36-9) 2.36.

**Comment by Nelbert442** [comment]
This would occur if you're using a daemon version higher than v117 , say the test release that was shared out recently or possibly the default remote node may be using it. For registration you can ignore this. However some functionality such as custom names etc may be limited with the new daemon version. Fixes will be investigated once the codebase has been updated and can be accommodated.

**Comment by aguythere** [comment]
Alright. For the record, I am pretty sure I am using the latest release version. I'll check as soon as possible, but for now I am closing the ticket as solved.
