### ISSUE TITLE
Engram wallet on on macOS Sonoma (14.1.1) crashes after 20-30 seconds

### ISSUE THREAD

**Issue by niekvolkert** [DEROFDN/Engram#16]
After having installed the Engram wallet on a macbook running macOS Sonoma, the Engram app crashes after 20-30 seconds. This became an issue after upgrading to Sonoma on the old Engram wallet as well.

**Comment by niekvolkert** [comment]
Duplicate posting

**Comment by stgoho** [comment]
Am finding this with the Windows wallet as well. Had it working fine under the previous version on Win10.

**Comment by DankFC** [comment]
Make sure to extract the archive (.zip) and place the Engram app into a new folder (name it "Engram") in your Applications folder. This should resolve any issues.
