### ISSUE TITLE
Netrunner 

### ISSUE THREAD

**Issue by viper1986** [DEROFDN/Engram#2]
Hello,

Button Configure on Netrunner is not working. When I click there is nothing going on.

Windows 10 x64

**Comment by Nelbert442** [comment]
Configure is not setup in current release, however will be there in upcoming release(s).

**Comment by viper1986** [comment]
Ok. Will wait then.

**Comment by Nelbert442** [comment]
Netrunner has been moved to its' own application and separated out from Engram itself. Please see https://github.com/DEROFDN/Netrunner
