### ISSUE TITLE
Low hashrate

### ISSUE THREAD

**Issue by Timofei88** [DEROFDN/Engram#4]
Hello. Running the wallet at the same time as mining on the video card reduces the hashrate of the video card. Windows 10. Is there a workaround for this problem?

**Comment by DankFC** [comment]
Currently uses half threads. Will add configuration soon.

**Comment by Nelbert442** [comment]
Netrunner has been moved to its' own configuration and separated from Engram. Please see https://github.com/DEROFDN/Netrunner for latest. Please also see latest Engram build via https://github.com/DEROFDN/Engram/releases/latest
