### ISSUE TITLE
Can't open wallet

### ISSUE THREAD

**Issue by jbarnes987** [DEROFDN/Engram#5]
Downloaded wallet and can't open it. I select wallet and enter password and it just closes. I am a newbie and have not clue. I do have norton 360

**Comment by DankFC** [comment]
You need to extract it first.

**Comment by jbarnes987** [comment]
Awesome, thanks. Its working now.

**Comment by Nelbert442** [comment]
Sounds like this issue was resolved earlier, but in the event there are other concerns and also to leverage latest - please download or build from latest release https://github.com/DEROFDN/Engram/releases/latest and feel free to re-open relevant issues should you still encounter them.
