### ISSUE TITLE
Android release not found 

### ISSUE THREAD

**Issue by Saikatsaha1996** [DEROFDN/Engram#6]
Where ican found Android version?

**Comment by Saikatsaha1996** [comment]
@DankFC where is Engram aarch64 version for Linux?

**Comment by DankFC** [comment]
> @DankFC where is Engram aarch64 version for Linux?

Look under the releases.

**Comment by Saikatsaha1996** [comment]
> > @DankFC where is Engram aarch64 version for Linux?
> 
> Look under the releases.

![Screenshot_2022-11-03-18-57-51-711_com android chrome](https://user-images.githubusercontent.com/72664192/199733208-600a324a-6fea-41cf-8d67-edadf9fddfca.jpg)
![Screenshot_2022-11-03-18-57-35-332_com android chrome](https://user-images.githubusercontent.com/72664192/199733228-ae34b8e1-c8d9-40c7-a080-b044219a440b.jpg)

**Comment by DankFC** [comment]
Android and iOS builds will be closer to our v1 release

**Comment by Saikatsaha1996** [comment]
> Android and iOS builds will be closer to our v1 release

Okay thank you
