### ISSUE TITLE
engram cant open wallet

### ISSUE THREAD

**Issue by ecostar11** [DEROFDN/Engram#7]
I cant login. Enter pass, press enter and nothing happens. At the bottom, the indicator, in the form of 3 dots, was green, now yellow

**Comment by Gerrycan2** [comment]
I have the same problem.

**Comment by Kabum80** [comment]
I have the same problem.

**Comment by DankFC** [comment]
Try restoring defaults in settings then restart Engram.

**Comment by Nelbert442** [comment]
Please download or build from latest release https://github.com/DEROFDN/Engram/releases/latest and feel free to re-open relevant issues should you still encounter them.
